name: Bug report
description: Report a reproducible bug or regression in this library.
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Before submitting
      options:
        - label: I tested using the latest version
          required: true
        - label: I checked for duplicate issues
          required: true
        - label: I have enabled `enableDebug={true}` prop and included console logs below
          required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - iOS
        - Android
        - Web (Expo)
        - Web (RN Web)
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        Run: `npm ls react-native react react-native-google-places-textinput` and paste the result here
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: |
        Provide a clear and concise description of what the bug is.
        If needed, you can also provide other samples: error messages / stack traces, screenshots, gifs, etc.
    validations:
      required: true

  - type: textarea
    id: debug-logs
    attributes:
      label: Debug logs (with enableDebug={true})
      description: Console logs starting with `[GooglePlacesTextInput:...]`
      render: text

